spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/travel
    username: admin
    password: 1234
    driverClassName: org.postgresql.Driver